// Copyright 2008 Thiago H. de Paula Figueiredo
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package net.sf.arsmachina.tapestrycrud;

import net.sf.arsmachina.tapestrycrud.components.ActionLinks;

import org.apache.tapestry5.beaneditor.BeanModel;
import org.apache.tapestry5.corelib.components.Grid;

/**
 * Class that holds some constants related to tapestry-crud.
 * 
 * @author Thiago H. de Paula Figueiredo (ThiagoHP)
 */
final public class Constants {
	
	/**
	 * Event generated by the remove link in the {@link ActionLinks} component.
	 */
	public static final String REMOVE_OBJECT_ACTION = "removeObject";

	/**
	 * Form id (t:id). All event handler methods is this class expect a form with this id.
	 */
	public static final String FORM_ID = "form";

	/**
	 * Message shown after a successful object save or update.
	 */
	public static final String MESSAGE_SAVEORUPDATE_SUCCESS = "message.success.saveorupdate";

	/**
	 * Tapestry-CRUD CSS asset path.
	 */
	public static final String TAPESTRY_CRUD_CSS_ASSET = "classpath:/net/sf/arsmachina/tapestrycrud/components/tapestry-crud.css";

	/**
	 * Remove object success message key.
	 */
	public static final String MESSAGE_SUCCESS_REMOVE = "message.success.remove";

	/**
	 * Name of the pseudo-property added to the {@link BeanModel} returned by
	 * {@link #getBeanModel()} to hold actions related to an object in a {@link Grid}.
	 */
	public static final String ACTION_PROPERTY_NAME = "action";

	/**
	 * Name of the pseudo-property added to the {@link BeanModel} returned by
	 * {@link #getBeanModel()} to hold actions related to an object in a {@link Grid}.
	 */
	public static final String REMOVE_COMPONENT_ID = "remove";

	/**
	 * Default zone ID to be returned by AJAX form submissions.
	 */
	public static final String DEFAULT_FORM_ZONE_ID = "zone";

	/**
	 * Default block ID to be returned by AJAX form submissions.
	 */
	public static final String DEFAULT_FORM_BLOCK_ID = "block";

	/**
	 * Single constructor of this class.
	 */
	private Constants() {
	}

	/**
	 * New object event.
	 */
	public static final String NEW_OBJECT_EVENT = "newObject";

}
